GET http://localhost:3000/instrument

POST http://localhost:3000/instrument HTTP/1.1
content-type: application/json

{	
	"ticker": "eurusd",
    "Name": "Euro US Dollar",
    "price": 1.232345
}

POST http://localhost:3000/instrument HTTP/1.1
content-type: application/json

{	
	"ticker": "usdjpy",
    "Name": "US Dollar Japaneese Yen",
    "price": 0.232345
}

POST http://localhost:3000/instrument HTTP/1.1
content-type: application/json

{	
	"ticker": "audusd",
    "Name": "US Dollar Australian Dollar",
    "price": 0.232345
}


GET http://localhost:3000/instrument/5df4f562cf1b9015782955c5


PUT http://localhost:3000/instrument/5df4f562cf1b9015782955c5 HTTP/1.1
content-type: application/json

{	
	"ticker": "usdncc",
    "Name": "US Dollar Nuca Colla Caps",
    "price": 10.232345
}